version: "2.1"
services:
    build_apm_php:
        build:
            context: .
            dockerfile: image/Dockerfile
        volumes:
          - ../:/source
#        command: sleep 100000
        command: sh -c "cd project && cmake --preset linux-x86-64-release && cmake --build --preset linux-x86-64-release "

    build_apm_php_musl:
        build:
            context: .
            dockerfile: image/Dockerfile_musl
        volumes:
          - ../:/source
        command: sleep 100000
